# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  dotnet-build:

    # runs-on: ubuntu-latest
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
    container:
      image: alpine/git
    permissions:
      actions: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      # with:
      #   token: ${{ secrets.ACTIONS_TOKEN }}
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   run:
    #   with:
    #     dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        pwd
        ls
        cd ./App_ma
        dotnet restore
    - name: Build
      run: |
        cd ./App_ma
        dotnet build --no-restore
    - name: Test
      run: |
        cd ./App_ma
        dotnet test --no-build --verbosity normal
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-artifacts
        path: ./App_ma  

  docker-build:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
    needs: dotnet-build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dotnet-artifacts
      - name: Build Docker image
        run: |
          pwd
          ls
          docker build -t github/counter-image -f ./App_ma/Dockerfile ./App_ma


  
